// flow-typed signature: 4d5f57fcb1a31a3650fce60994c861cd
// flow-typed version: <<STUB>>/svg-url-loader_v^7.1.1/flow_v0.169.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-url-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg-url-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svg-url-loader/src/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svg-url-loader/index' {
  declare module.exports: $Exports<'svg-url-loader'>;
}
declare module 'svg-url-loader/index.js' {
  declare module.exports: $Exports<'svg-url-loader'>;
}
declare module 'svg-url-loader/src/loader.js' {
  declare module.exports: $Exports<'svg-url-loader/src/loader'>;
}
